# Generated by Django 5.0.6 on 2024-07-07 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='home_phone',
            new_name='primary_phone',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='mobile_phone',
            new_name='secondary_phone',
        ),
        migrations.RemoveField(
            model_name='member',
            name='work_phone',
        ),
    ]
