# Generated by Django 4.1 on 2024-06-18 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_familymember_locker_payment_reservation_delete_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='last_login',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
