# Generated by Django 5.0.6 on 2024-06-30 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_alter_member_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='bunk',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='locker',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='member',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='reservation',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='member',
        ),
        migrations.RenameField(
            model_name='locker',
            old_name='locker_number',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='locker',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='locker',
            name='members_assigned',
            field=models.ManyToManyField(blank=True, related_name='lockers', to='member.member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='Bunk',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
