# Generated by Django 5.0.6 on 2024-06-30 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_remove_reservation_bunk_remove_payment_locker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
