# Generated by Django 5.0.6 on 2024-06-30 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_member_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
