# Generated by Django 5.0.6 on 2024-07-09 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bunk',
            name='sub_area',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
