# Generated by Django 4.1 on 2024-06-17 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='emergency_contact',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='emergency_contact_phone',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='member',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(default='Primary Member', max_length=25),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(default=None, max_length=254, unique=True),
        ),
    ]
