# Generated by Django 4.1 on 2024-06-17 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_member_emergency_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='username',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
