# Generated by Django 5.0.6 on 2024-06-30 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0018_remove_guest_cnic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='bookedservice',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='bookedservice',
            name='service',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='room',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='services',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_type',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.DeleteModel(
            name='Billing',
        ),
        migrations.DeleteModel(
            name='BookedService',
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='RoomType',
        ),
    ]
